### ISSUE TITLE
add api to load custom dict

### ISSUE THREAD

**Issue by ghost** [newebug/node-analyzer#1]
can you add a option to load custom dict or if we can do this know please wrtie document, thanks

**Comment by newebug** [comment]
Good option, I will add this api in just few days.

**Comment by newebug** [comment]
I update the Segmenter constructor, following code to using custom dictionary:
  ```
var opts = {
    MainDictPath: 'your_dict_folder/main.dic',
    SurnameDictPath: 'your_dict_folder/dict/surname.dic',
    QuantifierDictPath: 'your_dict_folder/dict/quantifier.dic',
    SuffixDictPath: 'your_dict_folder/dict/suffix.dic',
    PrepDictPath: 'your_dict_folder/dict/preposition.dic',
    StopWordDictPath: 'your_dict_folder/dict/stopword.dic',
  };
  var segmenter = new Segmenter(opts);
```

If any problem, please let me know. Thanks

**Comment by ghost** [comment]
i'm sorry, but how can i load custom dict named "mydict.dic" under dir `custom`

**Comment by newebug** [comment]
```
var opts = {
  MainDictPath: 'your_dict_folder/mydict.dic'
}

var segmenter = new Segmenter(opts);
```

**Comment by ghost** [comment]
@newebug  thanks for help, but there is no way to use the main.dic and custom mydict.dic at the same time?  
how about add api to config this file `node-analyzer/lib/config.js`
the content now is 
```
module.exports = {
	// Analyzer 扩展配置
	ext_dict: [/*'./dict/custom/mydict.dic', './dict/custom/single_word_low_freq.dic'*/],
	
	// 用户可以在这里配置自己的扩展停止词字典
	ext_stopwords: [/*'./dict/custom/ext_stopword.dic'*/]
};
```
is it possible add api to config the `ext_dict` variable so to keep main.dic and mydict.dic both?

**Comment by newebug** [comment]
Good suggestion.

I modified the Dictionary code, commit link: [here](https://github.com/newebug/node-analyzer/commit/c09d3e9d0a989fd2440422269e395678ff791b68)

Now we can overwrite the config with these code:

```
var opts = {
  MainDictPath: 'your_dict_folder/mydict.dic',
  Config: {
    ext_dict: ['./dict/custom/mydict.dic', './dict/custom/single_word_low_freq.dic'],
    ext_stopwords: ['./dict/custom/ext_stopword.dic']}
}
var segmenter = new Segmenter(opts);
```

**Comment by ghost** [comment]
thanks, good job!
